// vue-implementation/src/components/Tickets/TicketModal.vue
<template>
  <Teleport to="body">
    <div class="modal-overlay" @click="$emit('close')">
      <div class="modal" @click.stop>
        <div class="modal-header">
          <h2 class="modal-title">{{ ticket ? 'Edit Ticket' : 'Create New Ticket' }}</h2>
          <button class="btn-icon" @click="$emit('close')">
            <X :size="24" />
          </button>
        </div>
        <form @submit.prevent="handleSubmit">
          <div class="form-group">
            <label class="form-label">Title *</label>
            <input
              type="text"
              :class="['form-input', { error: errors.title }]"
              placeholder="Enter ticket title"
              v-model="formData.title"
            />
            <div v-if="errors.title" class="error-message">
              <AlertCircle :size="16" />
              {{ errors.title }}
            </div>
          </div>
          <div class="form-group">
            <label class="form-label">Description</label>
            <textarea
              class="form-textarea"
              placeholder="Enter ticket description (optional)"
              v-model="formData.description"
            />
          </div>
          <div class="form-group">
            <label class="form-label">Status *</label>
            <select
              :class="['form-select', { error: errors.status }]"
              v-model="formData.status"
            >
              <option value="open">Open</option>
              <option value="in_progress">In Progress</option>
              <option value="closed">Closed</option>
            </select>
            <div v-if="errors.status" class="error-message">
              <AlertCircle :size="16" />
              {{ errors.status }}
            </div>
          </div>
          <div class="form-group">
            <label class="form-label">Priority</label>
            <select class="form-select" v-model="formData.priority">
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
            </select>
          </div>
          <div class="modal-actions">
            <button type="button" class="btn btn-secondary" @click="$emit('close')">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary">
              {{ ticket ? 'Update' : 'Create' }} Ticket
            </button>
          </div>
        </form>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { reactive, ref, watch } from 'vue';
import { X, AlertCircle } from 'lucide-vue-next';
import { useToast } from '../../composables/useToast';

const props = defineProps({
  ticket: {
    type: Object,
    default: null
  }
});

const emit = defineEmits(['close', 'save']);
const { showToast } = useToast();

const formData = reactive({
  title: '',
  description: '',
  status: 'open',
  priority: 'medium'
});

const errors = ref({});

// Watch for ticket prop changes to populate form
watch(() => props.ticket, (newTicket) => {
  if (newTicket) {
    formData.title = newTicket.title;
    formData.description = newTicket.description || '';
    formData.status = newTicket.status;
    formData.priority = newTicket.priority || 'medium';
  } else {
    formData.title = '';
    formData.description = '';
    formData.status = 'open';
    formData.priority = 'medium';
  }
}, { immediate: true });

const handleSubmit = () => {
  const newErrors = {};

  if (!formData.title.trim()) {
    newErrors.title = 'Title is required';
  }

  if (!formData.status) {
    newErrors.status = 'Status is required';
  } else if (!['open', 'in_progress', 'closed'].includes(formData.status)) {
    newErrors.status = 'Status must be open, in_progress, or closed';
  }

  errors.value = newErrors;

  if (Object.keys(newErrors).length === 0) {
    const ticketData = {
      ...props.ticket,
      ...formData,
      id: props.ticket?.id || Date.now().toString(),
      createdAt: props.ticket?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
    
    emit('save', ticketData);
    showToast(
      props.ticket ? 'Ticket updated successfully!' : 'Ticket created successfully!',
      'success'
    );
  }
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.modal {
  background: white;
  border-radius: 16px;
  padding: 2rem;
  width: 100%;
  max-width: 500px;
  max-height: 90vh;
  overflow-y: auto;
  position: relative;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.modal-title {
  font-size: 1.5rem;
  font-weight: 600;
  color: #1f2937;
}

.modal-actions {
  display: flex;
  gap: 1rem;
  margin-top: 2rem;
}

.modal-actions .btn {
  flex: 1;
}
</style>

// react-implementation/src/components/Tickets/TicketModal.jsx
import React, { useState } from 'react';
import { X, AlertCircle } from 'lucide-react';
import './TicketModal.css';

const TicketModal = ({ ticket, onClose, onSave, showToast }) => {
  const [formData, setFormData] = useState({
    title: ticket?.title || '',
    description: ticket?.description || '',
    status: ticket?.status || 'open',
    priority: ticket?.priority || 'medium'
  });
  const [errors, setErrors] = useState({});

  const handleSubmit = (e) => {
    e.preventDefault();
    const newErrors = {};

    if (!formData.title.trim()) {
      newErrors.title = 'Title is required';
    }

    if (!formData.status) {
      newErrors.status = 'Status is required';
    } else if (!['open', 'in_progress', 'closed'].includes(formData.status)) {
      newErrors.status = 'Status must be open, in_progress, or closed';
    }

    setErrors(newErrors);

    if (Object.keys(newErrors).length === 0) {
      onSave({
        ...ticket,
        ...formData,
        id: ticket?.id || Date.now().toString(),
        createdAt: ticket?.createdAt || new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });
      showToast(
        ticket ? 'Ticket updated successfully!' : 'Ticket created successfully!',
        'success'
      );
      onClose();
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2 className="modal-title">{ticket ? 'Edit Ticket' : 'Create New Ticket'}</h2>
          <button className="btn-icon" onClick={onClose}>
            <X size={24} />
          </button>
        </div>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label">Title *</label>
            <input
              type="text"
              className={`form-input ${errors.title ? 'error' : ''}`}
              placeholder="Enter ticket title"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            />
            {errors.title && (
              <div className="error-message">
                <AlertCircle size={16} />
                {errors.title}
              </div>
            )}
          </div>
          <div className="form-group">
            <label className="form-label">Description</label>
            <textarea
              className="form-textarea"
              placeholder="Enter ticket description (optional)"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            />
          </div>
          <div className="form-group">
            <label className="form-label">Status *</label>
            <select
              className={`form-select ${errors.status ? 'error' : ''}`}
              value={formData.status}
              onChange={(e) => setFormData({ ...formData, status: e.target.value })}
            >
              <option value="open">Open</option>
              <option value="in_progress">In Progress</option>
              <option value="closed">Closed</option>
            </select>
            {errors.status && (
              <div className="error-message">
                <AlertCircle size={16} />
                {errors.status}
              </div>
            )}
          </div>
          <div className="form-group">
            <label className="form-label">Priority</label>
            <select
              className="form-select"
              value={formData.priority}
              onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
            </select>
          </div>
          <div className="modal-actions">
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button type="submit" className="btn btn-primary">
              {ticket ? 'Update' : 'Create'} Ticket
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default TicketModal;
